### ISSUE TITLE
Runtime error on macOS High Sierra (“Cannot find module ./trie”)

### ISSUE THREAD

**Issue by aral** [mafintosh/hypervision#39]
## To reproduce

  * macOS High Sierra 10.13.5 (17F77)
  * Node.js v8.11.1
  * NVM v6.1.0
  * Electron Version 1.4.6 (1.4.6)

1. Following instructions in the readme
2. App launches

## What should happen

Interface should load.

## What actually happens

Blank window.

Error in console:

```
Uncaught Error: Cannot find module './trie' (module.js:457)
```

**Comment by aral** [comment]
A better stack trace after upgrading Electron to 2.0.2:

```bash
Uncaught Error: Cannot find module './trie'
    at Module._resolveFilename (module.js:543)
    at Function.Module._resolveFilename (/Users/aral/sandbox/dat/hypervision/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35)
    at Function.Module._load (module.js:473)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
    at o (bundle.js:1)
    at bundle.js:1
    at Object.<anonymous> (bundle.js:780)
    at Object.14../trie (bundle.js:857)
    at o (bundle.js:1)
```
